spring:
  application:
    name: EstudandoSpringBoot

  datasource:
    url: ${DB_URL}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#Configurações do JPA // HIBERNATES
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true



